import { useMemo } from 'react'
import type { Player, Report } from '../types'
import { getVerdictBreakdown, getConsensus, getVerdictBucket } from '../utils/calculations'
import { formatDate, formatScoutName } from '../utils/formatting'
import Card from './ui/Card'
import Badge from './ui/Badge'

interface AnalysisTabProps {
  player: Player
  reports: Report[]
}

const consensusDisplay: Record<string, { emoji: string; label: string }> = {
  Positive: { emoji: '🟢', label: 'Positive' },
  'Watch Again': { emoji: '🟡', label: 'Watch Again' },
  Mixed: { emoji: '🟡', label: 'Mixed' },
  Negative: { emoji: '🔴', label: 'Negative' },
}

const verdictVariant: Record<string, 'success' | 'warning' | 'danger'> = {
  Sign: 'success',
  Watch: 'warning',
  Forget: 'danger',
}

export default function AnalysisTab({ player, reports }: AnalysisTabProps) {
  const breakdown = useMemo(() => getVerdictBreakdown(reports), [reports])
  const consensus = useMemo(() => getConsensus(breakdown), [breakdown])
  const scoutCount = useMemo(
    () => new Set(reports.map((r) => formatScoutName(r.scout_first_name, r.scout_last_name))).size,
    [reports],
  )
  const recentReports = useMemo(
    () =>
      [...reports]
        .sort((a, b) => {
          const dateA = a.fixture_date ? new Date(a.fixture_date).getTime() : 0
          const dateB = b.fixture_date ? new Date(b.fixture_date).getTime() : 0
          return dateB - dateA
        })
        .slice(0, 5),
    [reports],
  )

  const pct = (count: number) => (breakdown.total > 0 ? Math.round((count / breakdown.total) * 100) : 0)

  const fallbackSummary =
    breakdown.total > 0
      ? `Based on ${breakdown.total} reports: ${pct(breakdown.sign)}% recommend signing, ${pct(
          breakdown.watch,
        )}% suggest watching, ${pct(breakdown.forget)}% say forget.`
      : 'No scout reports available yet.'

  const { emoji, label } = consensusDisplay[consensus]

  return (
    <div className="p-4 space-y-4">
      <Card className="p-4">
        <div className="text-xs uppercase tracking-wide text-muted mb-2">AI Summary</div>
        <blockquote className="text-sm text-ink italic border-l-2 border-primary/40 pl-3">
          {player.scout_summary || fallbackSummary}
        </blockquote>
      </Card>

      <div className="grid grid-cols-3 gap-3">
        <Card className="p-3 bg-success/5 border-success/20">
          <div className="text-xs text-muted">Sign</div>
          <div className="text-xl font-bold text-success">{breakdown.sign}</div>
          <div className="text-xs text-muted">{pct(breakdown.sign)}%</div>
        </Card>
        <Card className="p-3 bg-warning/5 border-warning/20">
          <div className="text-xs text-muted">Watch Again</div>
          <div className="text-xl font-bold text-warning">{breakdown.watch}</div>
          <div className="text-xs text-muted">{pct(breakdown.watch)}%</div>
        </Card>
        <Card className="p-3 bg-danger/5 border-danger/20">
          <div className="text-xs text-muted">Forget</div>
          <div className="text-xl font-bold text-danger">{breakdown.forget}</div>
          <div className="text-xs text-muted">{pct(breakdown.forget)}%</div>
        </Card>
      </div>

      <Card className="p-4 flex items-center justify-between flex-wrap gap-2">
        <div className="flex items-center gap-2">
          <span className="text-xl">{emoji}</span>
          <span className="font-semibold text-ink">{label}</span>
        </div>
        <span className="text-xs text-muted">
          {breakdown.total} reports from {scoutCount} scout{scoutCount === 1 ? '' : 's'}
        </span>
      </Card>

      <div>
        <div className="text-xs uppercase tracking-wide text-muted mb-2">Recent Verdicts</div>
        {recentReports.length === 0 ? (
          <p className="text-sm text-muted">No reports yet.</p>
        ) : (
          <ul className="space-y-2">
            {recentReports.map((report) => (
              <li key={report.id} className="flex items-center justify-between text-sm bg-white rounded-md border border-gray-200 px-3 py-2">
                <div>
                  <span className="font-medium text-ink">
                    {formatScoutName(report.scout_first_name, report.scout_last_name)}
                  </span>
                  <span className="text-muted"> · {formatDate(report.fixture_date)}</span>
                </div>
                {report.verdict && (
                  <Badge variant={verdictVariant[getVerdictBucket(report.verdict) ?? ''] ?? 'neutral'}>
                    {report.verdict}
                  </Badge>
                )}
              </li>
            ))}
          </ul>
        )}
      </div>

      <p className="text-xs text-muted text-center">
        Generated by AI based on {breakdown.total} reports from {scoutCount} scout{scoutCount === 1 ? '' : 's'}
      </p>
    </div>
  )
}
